import { Property, Product, Transaction, VerificationTask, LandApp } from '../types';

export const PROPERTIES: Property[] = [
  {
    id: 'p1',
    title: 'Luxury 5 Bedroom Detached Duplex',
    price: 150000000,
    location: 'Lekki Phase 1, Lagos',
    type: 'sale',
    category: 'house',
    beds: 5,
    baths: 6,
    sqft: 4500,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/b9cebb6e-cc53-4bde-bbec-8e27656f3e98/luxury-house-lagos-38137fa2-1783444320729.webp',
    verified: true,
    description: 'A masterpiece of modern architecture situated in the heart of Lekki Phase 1. This property features premium finishes, a swimming pool, and smart home automation.',
    amenities: ['Swimming Pool', 'Gym', '24/7 Security', 'Smart Home', "Boy's Quarters"],
    agent: {
      name: 'Chidi Okafor',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chidi',
      phone: '+234 801 234 5678',
      email: 'chidi@landandtrust.ng'
    }
  },
  {
    id: 'p2',
    title: 'Modern 3 Bedroom Apartment',
    price: 85000000,
    location: 'Maitama, Abuja',
    type: 'sale',
    category: 'apartment',
    beds: 3,
    baths: 4,
    sqft: 2200,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/b9cebb6e-cc53-4bde-bbec-8e27656f3e98/apartment-abuja-c2e30c2e-1783444320699.webp',
    verified: true,
    description: 'Exquisite 3 bedroom apartment in the prestigious Maitama district. Offers panoramic views of the city and top-notch security.',
    amenities: ['Elevator', 'CCTV', 'Power Backup', 'Parking Space'],
    agent: {
      name: 'Amina Yusuf',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amina',
      phone: '+234 802 345 6789',
      email: 'amina@landandtrust.ng'
    }
  },
  {
    id: 'p3',
    title: 'Commercial Land in Ibeju-Lekki',
    price: 45000000,
    location: 'Ibeju-Lekki, Lagos',
    type: 'sale',
    category: 'land',
    beds: 0,
    baths: 0,
    sqft: 600,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800',
    verified: false,
    description: 'Prime commercial land strategically located near the Dangote Refinery. Excellent investment opportunity with high appreciation potential.',
    amenities: ['Dry Land', 'Fenced', 'C of O'],
    agent: {
      name: 'Oluwaseun Balogun',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olu',
      phone: '+234 803 456 7890',
      email: 'olu@landandtrust.ng'
    }
  },
  {
    id: 'p4',
    title: 'GOLD City Annex',
    price: 3500000,
    location: 'Ubani Ibeku, Umuahia, Abia State',
    type: 'sale',
    category: 'land',
    beds: 0,
    baths: 0,
    sqft: 0,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/b9cebb6e-cc53-4bde-bbec-8e27656f3e98/gold-city-annex-card-c687ee54-1783941561757.webp',
    verified: true,
    description: 'Prime investment opportunity in the heart of Umuahia. GOLD City Annex offers 25 verified and surveyed plots in a secure, access-controlled layout. Each plot comes with a Certificate of Occupancy, surveyed boundaries, and motorable road access. Perfect for building your dream home or a lucrative real estate investment.',
    amenities: ['Verified Survey', 'Registered Layout', 'Motorable Road', 'Power Connection', 'Perimeter Fencing', 'C of O', 'Access Gate'],
    plotsAvailable: 25,
    priceLabel: '₦3.5M per plot',
    agent: {
      name: 'Nkechi Eze',
      image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nkechi',
      phone: '+234 804 567 8901',
      email: 'nkechi@landandtrust.ng'
    }
  }
];

export const PRODUCTS: Product[] = [
  {
    id: 'pr1',
    name: '5kVA Solar Power System',
    price: 2500000,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/b9cebb6e-cc53-4bde-bbec-8e27656f3e98/solar-installation-cac9976a-1783444319699.webp',
    category: 'Solar Systems',
    rating: 4.8,
    reviews: 24,
    description: 'Complete 5kVA solar solution for medium-sized homes. Includes panels, inverter, and lithium batteries.',
    specifications: {
      'Capacity': '5kVA / 48V',
      'Panels': '8 x 450W Mono',
      'Battery': '10kWh Lithium',
      'Warranty': '5 Years'
    }
  },
  {
    id: 'pr2',
    name: 'Portable Solar Generator',
    price: 450000,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/b9cebb6e-cc53-4bde-bbec-8e27656f3e98/solar-generator-3e452e0a-1783444320586.webp',
    category: 'Generators',
    rating: 4.5,
    reviews: 12,
    description: 'Compact and powerful solar generator for camping, emergency backup, and small appliances.',
    specifications: {
      'Capacity': '1000Wh',
      'Output': '1000W AC',
      'Charging': 'Solar / AC / Car',
      'Weight': '11kg'
    }
  },
  {
    id: 'pr3',
    name: 'Lithium Battery 10kWh',
    price: 850000,
    image: 'https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?auto=format&fit=crop&q=80&w=800',
    category: 'Accessories',
    rating: 4.9,
    reviews: 31,
    description: 'High-capacity lithium iron phosphate battery for solar energy storage. Long cycle life and built-in BMS.',
    specifications: {
      'Capacity': '10kWh / 48V',
      'Chemistry': 'LiFePO4',
      'Cycle Life': '6000+ cycles',
      'Warranty': '10 Years'
    }
  },
  {
    id: 'pr4',
    name: 'Hybrid Inverter 5kVA',
    price: 420000,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800',
    category: 'Accessories',
    rating: 4.7,
    reviews: 19,
    description: 'Smart hybrid inverter with MPPT charge controller. Seamless grid-tie and off-grid switching.',
    specifications: {
      'Power': '5kVA / 48V',
      'MPPT': 'Built-in 80A',
      'Transfer Time': '<10ms',
      'Efficiency': '97.5%'
    }
  },
  {
    id: 'pr5',
    name: 'Solar Panel 450W Mono',
    price: 95000,
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&q=80&w=800',
    category: 'Accessories',
    rating: 4.6,
    reviews: 42,
    description: 'High-efficiency monocrystalline solar panel. Tier-1 certified with excellent low-light performance.',
    specifications: {
      'Power': '450W',
      'Type': 'Monocrystalline',
      'Efficiency': '21.3%',
      'Warranty': '25 Years'
    }
  }
];

export const BIOGAS_PRODUCTS: Product[] = [
  {
    id: 'bg1',
    name: 'Residential Digester',
    price: 750000,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/b9cebb6e-cc53-4bde-bbec-8e27656f3e98/residential-biogas-digester-72c80644-1783698577020.webp',
    category: 'Biogas Systems',
    rating: 4.7,
    reviews: 18,
    description: 'A compact and efficient biogas system for residential use, converting kitchen waste into cooking gas and liquid fertilizer.',
    specifications: {
      'Capacity': '2 m³',
      'Gas Output': '0.5 m³/day',
      'Feedstock': 'Kitchen Waste, Animal Manure',
      'Material': 'HDPE'
    }
  },
  {
    id: 'bg2',
    name: 'Commercial Biogas System',
    price: 5500000,
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/b9cebb6e-cc53-4bde-bbec-8e27656f3e98/residential-biogas-digester-72c80644-1783698577020.webp',
    category: 'Biogas Systems',
    rating: 4.9,
    reviews: 9,
    description: 'A large-scale biogas plant for farms, factories, and communities. Generates significant energy and high-quality organic fertilizer.',
    specifications: {
      'Capacity': '50 m³',
      'Gas Output': '20 m³/day',
      'Feedstock': 'Industrial Waste, Large-scale Agricultural Waste',
      'Material': 'Reinforced Concrete & Steel'
    }
  }
];

export const TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    date: '2023-11-20',
    amount: 150000000,
    status: 'successful',
    method: 'Bank Transfer',
    propertyTitle: 'Luxury 5 Bedroom Detached Duplex'
  },
  {
    id: 't2',
    date: '2023-11-21',
    amount: 2500000,
    status: 'pending',
    method: 'Card',
    propertyTitle: '5kVA Solar Power System'
  }
];

export const LAND_APPS: LandApp[] = [
  {
    id: 'la-1',
    name: 'TerraMap GIS Pro',
    tagline: 'Advanced topographic & contour mapping suite',
    description: 'A professional-grade GIS platform for precision land mapping, contour analysis, and 3D terrain visualization. Supports multi-layer overlay, GPS field data import, and export to industry-standard formats. Ideal for surveyors, urban planners, and real estate developers.',
    category: 'gis-mapping',
    categoryLabel: 'GIS & Mapping',
    rating: 4.8,
    reviewsCount: 342,
    icon: '🗺️',
    bannerImage: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'GeoVista Technologies',
    developerUrl: 'https://geovista.tech',
    version: '4.2.1',
    size: '84 MB',
    lastUpdated: '2024-11-15',
    installed: false,
    status: 'available',
    pricing: 'Subscription',
    tags: ['GIS', 'Topography', 'Contour', '3D Terrain', 'GPS'],
    features: [
      'Multi-layer map overlay with custom styling',
      'Real-time GPS field data synchronization',
      '3D terrain rendering with elevation profiles',
      'Export to DXF, SHP, GeoJSON, KML formats',
      'Automated contour line generation',
      'Slope analysis & watershed delineation',
    ],
    permissions: ['Location (GPS)', 'Storage', 'Camera', 'Network'],
    documentationUrl: 'https://docs.geovista.tech/terramap',
    accentColor: 'emerald',
  },
  {
    id: 'la-2',
    name: 'SoilSense AI',
    tagline: 'Precision soil quality & moisture analyzer',
    description: 'AI-powered soil analysis platform that provides real-time soil quality metrics, moisture content, pH levels, and nutrient recommendations. Integrates with IoT sensors for continuous monitoring and generates actionable reports for agricultural land management.',
    category: 'soil-agtech',
    categoryLabel: 'Soil & AgTech',
    rating: 4.7,
    reviewsCount: 256,
    icon: '🌱',
    bannerImage: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'AgriSense Labs',
    developerUrl: 'https://agrisense.io',
    version: '3.0.5',
    size: '62 MB',
    lastUpdated: '2024-10-22',
    installed: false,
    status: 'available',
    pricing: 'Freemium',
    tags: ['Soil', 'AI', 'IoT', 'Agriculture', 'Sensors'],
    features: [
      'Real-time soil moisture & temperature monitoring',
      'AI-driven nutrient deficiency detection',
      'Automated irrigation scheduling recommendations',
      'Multi-field dashboard with historical trends',
      'IoT sensor integration (Moisture, pH, NPK)',
      'PDF report generation for compliance',
    ],
    permissions: ['Bluetooth', 'Location', 'Storage', 'Notifications'],
    documentationUrl: 'https://docs.agrisense.io/soilsense',
    accentColor: 'amber',
  },
  {
    id: 'la-3',
    name: 'BoundarX Drone Surveyor',
    tagline: 'High-precision drone photogrammetry & boundary mapping',
    description: 'A comprehensive drone surveying platform that processes aerial imagery into accurate boundary maps, 3D models, and volumetric measurements. Features automated flight planning, real-time georeferencing, and seamless integration with survey-grade GPS equipment.',
    category: 'drone-surveying',
    categoryLabel: 'Drone Surveying',
    rating: 4.9,
    reviewsCount: 189,
    icon: '🛸',
    bannerImage: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'AeroMap Solutions',
    developerUrl: 'https://aeromap.dev',
    version: '2.8.3',
    size: '128 MB',
    lastUpdated: '2024-12-01',
    installed: false,
    status: 'available',
    pricing: 'Subscription',
    tags: ['Drone', 'Photogrammetry', 'Boundary', '3D Model', 'Aerial'],
    features: [
      'Automated flight path planning with obstacle avoidance',
      'Real-time orthomosaic stitching & georeferencing',
      'High-res 3D point cloud & mesh generation',
      'Volumetric stockpile & cut/fill calculations',
      'Boundary marker detection with sub-centimeter accuracy',
      'Export to CAD, GIS, and BIM formats',
    ],
    permissions: ['Camera', 'Location (GPS)', 'Storage', 'Bluetooth', 'Network'],
    documentationUrl: 'https://docs.aeromap.dev/boundarx',
    accentColor: 'blue',
  },
  {
    id: 'la-4',
    name: 'ZoneGuard Compliance',
    tagline: 'Municipal zoning, setback & permit checker',
    description: 'Instant zoning compliance verification tool for land developers and property owners. Cross-references property boundaries with municipal zoning ordinances, setback requirements, and permit status. Reduces due diligence time from days to minutes.',
    category: 'zoning',
    categoryLabel: 'Zoning',
    rating: 4.5,
    reviewsCount: 178,
    icon: '🏛️',
    bannerImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'Urban Logic Inc.',
    developerUrl: 'https://urbanlogic.com',
    version: '1.6.2',
    size: '45 MB',
    lastUpdated: '2024-09-10',
    installed: false,
    status: 'available',
    pricing: 'Freemium',
    tags: ['Zoning', 'Compliance', 'Permits', 'Municipal', 'Regulations'],
    features: [
      'Automated zoning district lookup by address/parcel',
      'Setback & height restriction visual overlay',
      'Permit status tracking & renewal reminders',
      'Flood zone & environmental overlay analysis',
      'Multi-jurisdiction comparison tool',
      'PDF compliance report generation',
    ],
    permissions: ['Location', 'Network', 'Storage'],
    documentationUrl: 'https://docs.urbanlogic.com/zoneguard',
    accentColor: 'violet',
  },
  {
    id: 'la-5',
    name: 'ForestryTrack 360',
    tagline: 'Tree canopy & timber yield estimator',
    description: 'End-to-end forest management platform for timber yield estimation, tree canopy analysis, and carbon sequestration tracking. Uses satellite imagery and LiDAR data to provide accurate biomass calculations and harvest planning.',
    category: 'forestry',
    categoryLabel: 'Forestry',
    rating: 4.6,
    reviewsCount: 134,
    icon: '🌲',
    bannerImage: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'Canopy Dynamics',
    developerUrl: 'https://canopydynamics.com',
    version: '2.1.0',
    size: '72 MB',
    lastUpdated: '2024-11-28',
    installed: false,
    status: 'available',
    pricing: 'Subscription',
    tags: ['Forestry', 'Canopy', 'Timber', 'Carbon', 'LiDAR'],
    features: [
      'Satellite-based tree species classification',
      'Timber volume & yield projection modeling',
      'Carbon sequestration & biomass calculation',
      'Harvest scheduling with optimal routing',
      'Wildfire risk assessment & mitigation planning',
      'Regulatory compliance reporting (FSC, SFI)',
    ],
    permissions: ['Location', 'Camera', 'Storage', 'Network'],
    documentationUrl: 'https://docs.canopydynamics.com/forestrytrack',
    accentColor: 'green',
  },
  {
    id: 'la-6',
    name: 'AgriYield Planner',
    tagline: 'Crop rotation & land productivity forecaster',
    description: 'Smart agricultural planning tool that optimizes crop rotation cycles, predicts land productivity, and estimates yield based on soil data, historical patterns, and climate models. Maximizes ROI while maintaining soil health.',
    category: 'soil-agtech',
    categoryLabel: 'Soil & AgTech',
    rating: 4.4,
    reviewsCount: 211,
    icon: '🌾',
    bannerImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1592982537447-6e2c6c2e8a2b?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'FarmTech Global',
    developerUrl: 'https://farmtech.global',
    version: '5.0.1',
    size: '38 MB',
    lastUpdated: '2024-10-05',
    installed: false,
    status: 'available',
    pricing: 'Freemium',
    tags: ['Crops', 'Yield', 'Rotation', 'Productivity', 'Climate'],
    features: [
      'AI-powered crop rotation recommendations',
      'Historical yield analysis with trend forecasting',
      'Weather integration with 14-day forecast',
      'Soil health score tracking over time',
      'Multi-field comparison & benchmarking',
      'Profitability calculator with break-even analysis',
    ],
    permissions: ['Location', 'Network', 'Storage', 'Notifications'],
    documentationUrl: 'https://docs.farmtech.global/agriyield',
    accentColor: 'lime',
  },
  {
    id: 'la-7',
    name: 'LandValuate Engine',
    tagline: 'Real-time land pricing & comp analysis model',
    description: 'Enterprise-grade land valuation engine that provides instant property appraisals using machine learning models trained on thousands of transactions. Analyzes comps, market trends, zoning impact, and development potential to generate accurate valuations.',
    category: 'valuation',
    categoryLabel: 'Valuation',
    rating: 4.7,
    reviewsCount: 298,
    icon: '💎',
    bannerImage: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'Valure Intelligence',
    developerUrl: 'https://valure.ai',
    version: '3.4.0',
    size: '56 MB',
    lastUpdated: '2024-12-10',
    installed: false,
    status: 'available',
    pricing: 'Subscription',
    tags: ['Valuation', 'ML', 'Comps', 'Appraisal', 'Market'],
    features: [
      'ML-powered instant property valuation engine',
      'Comparable sales (comps) analysis with map view',
      'Development potential & highest-best-use analysis',
      'Market trend tracking with price heatmaps',
      'Zoning impact assessment on property value',
      'Automated appraisal report generation (AVM)',
    ],
    permissions: ['Location', 'Network', 'Storage'],
    documentationUrl: 'https://docs.valure.ai/landvaluate',
    accentColor: 'indigo',
  },
  {
    id: 'la-8',
    name: 'CadastralSync',
    tagline: 'Official land registry & title document sync tool',
    description: 'Secure digital platform that synchronizes with official land registries to verify title documents, track ownership history, and manage cadastral records. Streamlines the due diligence process with blockchain-verified document integrity.',
    category: 'cadastral',
    categoryLabel: 'Cadastral',
    rating: 4.3,
    reviewsCount: 167,
    icon: '📜',
    bannerImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'RegistryTech Solutions',
    developerUrl: 'https://registrytech.com',
    version: '1.2.4',
    size: '34 MB',
    lastUpdated: '2024-08-15',
    installed: false,
    status: 'available',
    pricing: 'Subscription',
    tags: ['Registry', 'Title', 'Cadastral', 'Blockchain', 'Compliance'],
    features: [
      'Real-time land registry synchronization',
      'Blockchain-verified document integrity checks',
      'Ownership history & chain of title visualization',
      'Automated encumbrance & lien detection',
      'Multi-jurisdiction title search integration',
      'Secure digital document vault with e-signatures',
    ],
    permissions: ['Network', 'Storage', 'Camera', 'Biometric'],
    documentationUrl: 'https://docs.registrytech.com/cadastralsync',
    accentColor: 'stone',
  },
  {
    id: 'la-9',
    name: 'EcoImpact Analyzer',
    tagline: 'Environmental impact assessment & compliance tool',
    description: 'Comprehensive environmental assessment platform for land development projects. Analyzes ecological impact, biodiversity scores, carbon footprint, and regulatory compliance requirements. Generates EIA reports aligned with national and international standards.',
    category: 'zoning',
    categoryLabel: 'Zoning',
    rating: 4.2,
    reviewsCount: 98,
    icon: '♻️',
    bannerImage: 'https://images.unsplash.com/photo-1516826957135-700998ea019c?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1536244636800-a3f74db0f3cf?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'EcoVista Analytics',
    developerUrl: 'https://ecovista.io',
    version: '2.0.0',
    size: '48 MB',
    lastUpdated: '2024-11-20',
    installed: false,
    status: 'available',
    pricing: 'Freemium',
    tags: ['EIA', 'Environmental', 'Biodiversity', 'Carbon', 'Compliance'],
    features: [
      'Automated ecological impact scoring',
      'Biodiversity index & habitat assessment',
      'Carbon footprint & offset calculator',
      'Regulatory compliance checklist (NEMA, EPA)',
      'Mitigation measure recommendation engine',
      'EIA report generation with stakeholder summaries',
    ],
    permissions: ['Location', 'Camera', 'Network', 'Storage'],
    documentationUrl: 'https://docs.ecovista.io/ecoimpact',
    accentColor: 'teal',
  },
  {
    id: 'la-10',
    name: 'GeoShare Connect',
    tagline: 'Team collaboration hub for geospatial data',
    description: 'Cloud-based collaboration platform for GIS teams to share, annotate, and version-control geospatial datasets. Features real-time co-editing, permission management, and integration with major GIS tools.',
    category: 'gis-mapping',
    categoryLabel: 'GIS & Mapping',
    rating: 4.1,
    reviewsCount: 145,
    icon: '🔗',
    bannerImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1200',
    screenshots: [
      'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&q=80&w=800',
      'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?auto=format&fit=crop&q=80&w=800',
    ],
    developer: 'GeoVista Technologies',
    developerUrl: 'https://geovista.tech',
    version: '1.8.1',
    size: '52 MB',
    lastUpdated: '2024-10-30',
    installed: false,
    status: 'available',
    pricing: 'Freemium',
    tags: ['Collaboration', 'GIS', 'Cloud', 'Team', 'Data'],
    features: [
      'Real-time geospatial data co-editing',
      'Version control with change history & rollback',
      'Role-based access control for teams',
      'Integration with QGIS, ArcGIS, & Google Earth',
      'Comment & annotation system on maps',
      'Automated data sync across devices',
    ],
    permissions: ['Network', 'Storage', 'Contacts'],
    documentationUrl: 'https://docs.geovista.tech/geoshare',
    accentColor: 'sky',
  },
];

export const VERIFICATION_TASKS: VerificationTask[] = [
  {
    id: 'v1',
    propertyTitle: 'Commercial Land in Ibeju-Lekki',
    status: 'pending',
    assignedTo: 'John Doe',
    dueDate: '2023-11-25',
    priority: 'high'
  },
  {
    id: 'v2',
    propertyTitle: 'Luxury 5 Bedroom Detached Duplex',
    status: 'approved',
    assignedTo: 'Jane Smith',
    dueDate: '2023-11-22',
    priority: 'medium'
  }
];